version: '3'

services:
  spark:
    image: jupyter/pyspark-notebook:latest
    container_name: spark-notebook
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - PYSPARK_PYTHON=python3
    volumes:
      - ./work:/home/jovyan/work
